export {default as Cart} from './Cart'
//export {default as Footer} from './Footer'
export {default as FooterBanner} from './Cart'
export {default as Banner} from './Banner'
export {default as Header} from './Header'
export {default as Layout} from './Cart'
export {default as Navbar} from './Cart'
export {default as Product} from './Cart'
export {default as Produtos} from './Produtos'
export {default as Produtosdois} from './Produtosdois'
export {default as Art} from './Art'

